atlas-client:
  build: ..
  dockerfile: ./deploy/ClientDockerfile
  container_name: atlas-client
  restart: always
  ports:
    - 3000:3000
  environment:
    - NODE_ENV=production
    - HOST=0.0.0.0
    - PORT=3000
    - ATLAS_APP={{ATLAS_APP}}
    - API_URL={{API_URL}}
    - AUTH_COOKIE_NAME={{AUTH_COOKIE_NAME}}
    - API_SWAGGER_URL={{API_SWAGGER_URL}}
    - GOOGLE_MAPS_API_KEY={{GOOGLE_MAPS_API_KEY}}
    - BOX_CLIENT_ID={{BOX_CLIENT_ID}}
    - DROPBOX_APP_KEY={{DROPBOX_APP_KEY}}
    - GOOGLE_DRIVE_CLIENT_ID={{GOOGLE_DRIVE_CLIENT_ID}}
    - GOOGLE_DRIVE_DEVELOPER_KEY={{GOOGLE_DRIVE_DEVELOPER_KEY}}
    - ONEDRIVE_CLIENT_ID={{ONEDRIVE_CLIENT_ID}}
