/* @flow */

export const AUTH_INITIALISE = 'AUTH_INITIALISE';
export const AUTH_INITIALISE_SUCCESS = 'AUTH_INITIALISE_SUCCESS';

export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP_FAIL = 'AUTH_SIGNUP_FAIL';

export const AUTH_SIGNIN = 'AUTH_SIGNIN';
export const AUTH_SIGNIN_SUCCESS = 'AUTH_SIGNIN_SUCCESS';
export const AUTH_SIGNIN_FAIL = 'AUTH_SIGNIN_FAIL';

export const AUTH_FORGOT_PASSWORD = 'AUTH_FORGOT_PASSWORD';
export const AUTH_FORGOT_PASSWORD_SUCCESS = 'AUTH_FORGOT_PASSWORD_SUCCESS';
export const AUTH_FORGOT_PASSWORD_FAIL = 'AUTH_FORGOT_PASSWORD_FAIL';

export const AUTH_RESET_PASSWORD = 'AUTH_RESET_PASSWORD';
export const AUTH_RESET_PASSWORD_SUCCESS = 'AUTH_RESET_PASSWORD_SUCCESS';
export const AUTH_RESET_PASSWORD_FAIL = 'AUTH_RESET_PASSWORD_FAIL';

export const AUTH_SIGNOUT = 'AUTH_SIGNOUT';
export const AUTH_SIGNOUT_SUCCESS = 'AUTH_SIGNOUT_SUCCESS';

export const AUTH_REQUEST_USER = 'AUTH_REQUEST_USER';
export const AUTH_REQUEST_USER_SUCCESS = 'AUTH_REQUEST_USER_SUCCESS';
export const AUTH_REQUEST_USER_FAIL = 'AUTH_REQUEST_USER_FAIL';

export const AUTH_UPDATE_USER = 'AUTH_UPDATE_USER';
export const AUTH_UPDATE_USER_SUCCESS = 'AUTH_UPDATE_USER_SUCCESS';
export const AUTH_UPDATE_USER_FAIL = 'AUTH_UPDATE_USER_FAIL';

export const AUTH_DELETE_USER = 'AUTH_DELETE_USER';
export const AUTH_DELETE_USER_SUCCESS = 'AUTH_DELETE_USER_SUCCESS';
export const AUTH_DELETE_USER_FAIL = 'AUTH_DELETE_USER_FAIL';

export const AUTH_UPDATE_FAILURE_REASON = 'AUTH_UPDATE_FAILURE_REASON';
export const AUTH_DELETE_FAILURE_REASON = 'AUTH_DELETE_FAILURE_REASON';

export const AUTH_VERIFY = 'AUTH_VERIFY';
export const AUTH_VERIFY_SUCCESS = 'AUTH_VERIFY_SUCCESS';
export const AUTH_VERIFY_FAIL = 'AUTH_VERIFY_FAIL';

export const REQUEST_ALL_USERS = 'REQUEST_ALL_USERS';
export const REQUEST_ALL_USERS_SUCCESS = 'REQUEST_ALL_USERS_SUCCESS';
export const REQUEST_ALL_USERS_FAIL = 'REQUEST_ALL_USERS_FAIL';

export const NEW_USER = 'NEW_USER';

export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';

export const REQUEST_USER = 'REQUEST_USER';
export const REQUEST_USER_SUCCESS = 'REQUEST_USER_SUCCESS';
export const REQUEST_USER_FAIL = 'REQUEST_USER_FAIL';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';

export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';

export const ASSIGN_USER_ROLE = 'ASSIGN_USER_ROLE';
export const ASSIGN_USER_ROLE_SUCCESS = 'ASSIGN_USER_ROLE_SUCCESS';
export const ASSIGN_USER_ROLE_FAIL = 'ASSIGN_USER_ROLE_FAIL';

export const REQUEST_ALL_ORGANISATIONS = 'REQUEST_ALL_ORGANISATIONS';
export const REQUEST_ALL_ORGANISATIONS_SUCCESS = 'REQUEST_ALL_ORGANISATIONS_SUCCESS';
export const REQUEST_ALL_ORGANISATIONS_FAIL = 'REQUEST_ALL_ORGANISATIONS_FAIL';

export const NEW_ORGANISATION = 'NEW_ORGANISATION';

export const CREATE_ORGANISATION = 'CREATE_ORGANISATION';
export const CREATE_ORGANISATION_SUCCESS = 'CREATE_ORGANISATION_SUCCESS';
export const CREATE_ORGANISATION_FAIL = 'CREATE_ORGANISATION_FAIL';

export const REQUEST_ORGANISATION = 'REQUEST_ORGANISATION';
export const REQUEST_ORGANISATION_SUCCESS = 'REQUEST_ORGANISATION_SUCCESS';
export const REQUEST_ORGANISATION_FAIL = 'REQUEST_ORGANISATION_FAIL';

export const UPDATE_ORGANISATION = 'UPDATE_ORGANISATION';
export const UPDATE_ORGANISATION_SUCCESS = 'UPDATE_ORGANISATION_SUCCESS';
export const UPDATE_ORGANISATION_FAIL = 'UPDATE_ORGANISATION_FAIL';

export const DELETE_ORGANISATION = 'DELETE_ORGANISATION';
export const DELETE_ORGANISATION_SUCCESS = 'DELETE_ORGANISATION_SUCCESS';
export const DELETE_ORGANISATION_FAIL = 'DELETE_ORGANISATION_FAIL';

export const ANALYSE_FILE_PREPARE = 'ANALYSE_FILE_PREPARE';
export const ANALYSE_FILE_UPLOAD = 'ANALYSE_FILE_UPLOAD';
export const ANALYSE_FILE_ANALYSE = 'ANALYSE_FILE_ANALYSE';
export const ANALYSE_FILE_ERROR = 'ANALYSE_FILE_ERROR';
export const ANALYSE_FILE_SUCCESS = 'ANALYSE_FILE_SUCCESS';
export const ANALYSE_FILE_PROGRESS = 'ANALYSE_FILE_PROGRESS';
export const ANALYSE_FILE_CANCEL = 'ANALYSE_FILE_CANCEL';

export const SET_NODE_HIGHLIGHTED = 'SET_NODE_HIGHLIGHTED';
export const UNSET_NODE_HIGHLIGHTED_ALL = 'UNSET_NODE_HIGHLIGHTED_ALL';

export const SET_METADATA = 'SET_METADATA';
export const POST_METADATA_FORM = 'POST_METADATA_FORM';

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
export const HIDE_ALL_NOTIFICATIONS = 'HIDE_ALL_NOTIFICATIONS';

export const REQUEST_EXPERIMENTS = 'REQUEST_EXPERIMENTS';
export const RECEIVE_EXPERIMENTS = 'RECEIVE_EXPERIMENTS';
