/* @flow */

export const ANALYSE_FILE = 'ANALYSE_FILE';
export const ANALYSE_FILE_CHECK = 'ANALYSE_FILE_CHECK';
export const ANALYSE_FILE_UPLOAD = 'ANALYSE_FILE_UPLOAD';
export const ANALYSE_FILE_PROCESS = 'ANALYSE_FILE_PROCESS';
export const ANALYSE_FILE_ERROR = 'ANALYSE_FILE_ERROR';
export const ANALYSE_FILE_SUCCESS = 'ANALYSE_FILE_SUCCESS';
export const ANALYSE_FILE_PROGRESS = 'ANALYSE_FILE_PROGRESS';
export const ANALYSE_FILE_CANCEL = 'ANALYSE_FILE_CANCEL';

export const SET_NODE_HIGHLIGHTED = 'SET_NODE_HIGHLIGHTED';
export const UNSET_NODE_HIGHLIGHTED_ALL = 'UNSET_NODE_HIGHLIGHTED_ALL';

export const SET_METADATA = 'SET_METADATA';
export const POST_METADATA_FORM = 'POST_METADATA_FORM';

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
export const HIDE_ALL_NOTIFICATIONS = 'HIDE_ALL_NOTIFICATIONS';

export const REQUEST_EXPERIMENTS = 'REQUEST_EXPERIMENTS';
export const RECEIVE_EXPERIMENTS = 'RECEIVE_EXPERIMENTS';
