export const ANALYSE_FILE = 'ANALYSE_FILE';
export const ANALYSE_FILE_ERROR = 'ANALYSE_FILE_ERROR';
export const ANALYSE_FILE_SUCCESS = 'ANALYSE_FILE_SUCCESS';
export const ANALYSE_FILE_PROGRESS = 'ANALYSE_FILE_PROGRESS';
export const ANALYSE_FILE_CANCEL = 'ANALYSE_FILE_CANCEL';

export const SET_NODE_HIGHLIGHTED = 'SET_NODE_HIGHLIGHTED';
export const UNSET_NODE_HIGHLIGHTED_ALL = 'UNSET_NODE_HIGHLIGHTED_ALL';
